spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*
      filters: stat,wall,slf4j

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false



  #    filters: stat,wall
#    max-active: 12
#    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration: # 以后它来指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true

#如果没有注释掉全局配置文件，springboot会忽略掉configuration的配置（现在的springboot版本会直接报错）
# 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中即可



